version: "3.9"

services:
  frontend:
  build: ./frontend
  container_name: ai-pply-frontend
  platform: linux/amd64   # Force AMD64 (x86) architecture
  ports:
    - "3000:3000"
  volumes:
    - ./frontend:/app:cached
  depends_on:
    - backend


  backend:
    build: ./backend
    container_name: ai-pply-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    env_file:
      - .env                      # Load OPENAI_API_KEY
    environment:
      - MONGO_URI=mongodb://mongo:27017/ai-pply

  mongo:
    image: mongo:6
    container_name: ai-pply-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
